name: Continuous integration
on: [push, pull_request]
env:
  # Bump this number to invalidate the Github-actions cache
  cache-invalidation-key: 0
  NIX_PATH: nixpkgs=https://github.com/NixOS/nixpkgs/archive/abfd31179174133ab8131139d650297bf4da63b7.tar.gz
  

jobs:
  cabal-build:
    name: cabal build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: "${{ env.NIX_PATH }}"
    - name: Cache Cabal dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          slides/dist-newstyle
        key: cabal-deps-${{ runner.os }}-${{ hashFiles('nix/sources.json') }}-v${{ env.cache-invalidation-key }}-${{ hashFiles('slides/slides.cabal') }}-${{ github.sha }}
        restore-keys: cabal-deps-${{ runner.os }}-${{ hashFiles('nix/sources.json') }}-v${{ env.cache-invalidation-key }}-${{ hashFiles('slides/slides.cabal') }}-
    - name: Build Nix dependencies
      run: nix-shell --pure --run "echo '=== Nix dependencies installed ==='"
    - name: Update Cabal's database
      run: nix-shell --pure --run "cabal update"
    - name: cabal build with build_hs.sh
      run: nix-shell --pure --run "cd slides && bash build_hs.sh"
